### ISSUE TITLE
Questions regarding the release date of this highly anticipated project.

### ISSUE THREAD

**Issue by Nima-Ra** [asjn3e/Mars#3]
While looking at this repository, a few questions came to my humble mind and I found no other place better than here to ask them.
I'm sure you know that this a highly anticipated project that a considerable amount of people are waiting for (including myself.) Unfortunately, there were no release dates in this repository so that made me wonder when is this project actually going to be finished? Is there a specific deadline that we are not aware of?
Thank you for your fantastic contributions to the community of JavaScript developers, Mr. Jafari.
We all look forward to your ambitious future projects.

**Comment by asjn3e** [comment]
> While looking at this repository, a few questions came to my humble mind and I found no other place better than here to ask them.
> I'm sure you know that this a highly anticipated project that a considerable amount of people are waiting for (including myself.) Unfortunately, there were no release dates in this repository so that made me wonder when is this project actually going to be finished? Is there a specific deadline that we are not aware of?
> Thank you for your fantastic contributions to the community of JavaScript developers, Mr. Jafari.
> We all look forward to your ambitious future projects.

Well i dont discuss with you because you're nima and  just to mention that in README i defined this repository as a repository for learning and practicing purposes

**Comment by asjn3e** [comment]
Hh
